# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(400, 410)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("chaos_3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.timerTab = QtGui.QWidget()
        self.timerTab.setObjectName(_fromUtf8("timerTab"))
        self.splitter = QtGui.QSplitter(self.timerTab)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 378, 358))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(6)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.timeLabel = QtGui.QLabel(self.splitter)
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.stopBtn = QtGui.QPushButton(self.widget)
        self.stopBtn.setObjectName(_fromUtf8("stopBtn"))
        self.horizontalLayout.addWidget(self.stopBtn)
        self.startBtn = QtGui.QPushButton(self.widget)
        self.startBtn.setObjectName(_fromUtf8("startBtn"))
        self.horizontalLayout.addWidget(self.startBtn)
        self.timeEdit = QtGui.QTimeEdit(self.widget)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.horizontalLayout.addWidget(self.timeEdit)
        self.tabWidget.addTab(self.timerTab, _fromUtf8(""))
        self.stopwatchTab = QtGui.QWidget()
        self.stopwatchTab.setObjectName(_fromUtf8("stopwatchTab"))
        self.gridLayoutWidget = QtGui.QWidget(self.stopwatchTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 124))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.timeLabel_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.timeLabel_2.setObjectName(_fromUtf8("timeLabel_2"))
        self.gridLayout_2.addWidget(self.timeLabel_2, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.stopBtn_2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.stopBtn_2.setObjectName(_fromUtf8("stopBtn_2"))
        self.horizontalLayout_2.addWidget(self.stopBtn_2)
        self.lapBtn = QtGui.QPushButton(self.gridLayoutWidget)
        self.lapBtn.setObjectName(_fromUtf8("lapBtn"))
        self.horizontalLayout_2.addWidget(self.lapBtn)
        self.startBtn_2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.startBtn_2.setObjectName(_fromUtf8("startBtn_2"))
        self.horizontalLayout_2.addWidget(self.startBtn_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.stopwatchTab)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 140, 378, 218))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.scrollArea = QtGui.QScrollArea(self.groupBox_2)
        self.scrollArea.setGeometry(QtCore.QRect(9, 9, 361, 201))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 199))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollAreaContentsWidget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.scrollAreaContentsWidget.setGeometry(QtCore.QRect(-1, -1, 361, 201))
        self.scrollAreaContentsWidget.setObjectName(_fromUtf8("scrollAreaContentsWidget"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.stopwatchTab, _fromUtf8(""))
        self.alarmTab = QtGui.QWidget()
        self.alarmTab.setObjectName(_fromUtf8("alarmTab"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.alarmTab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 310, 361, 41))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.addAlarmBtn = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.addAlarmBtn.setObjectName(_fromUtf8("addAlarmBtn"))
        self.horizontalLayout_3.addWidget(self.addAlarmBtn)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.alarmTab)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 0, 378, 311))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.scrollArea_2 = QtGui.QScrollArea(self.groupBox_3)
        self.scrollArea_2.setGeometry(QtCore.QRect(9, 9, 361, 291))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 359, 289))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.scrollAreaContentsWidget_2 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.scrollAreaContentsWidget_2.setGeometry(QtCore.QRect(-1, -1, 361, 291))
        self.scrollAreaContentsWidget_2.setObjectName(_fromUtf8("scrollAreaContentsWidget_2"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.addTab(self.alarmTab, _fromUtf8(""))
        self.tasksTab = QtGui.QWidget()
        self.tasksTab.setObjectName(_fromUtf8("tasksTab"))
        self.groupBox = QtGui.QGroupBox(self.tasksTab)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 378, 358))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 310, 361, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.addTask = QtGui.QPushButton(self.layoutWidget)
        self.addTask.setObjectName(_fromUtf8("addTask"))
        self.horizontalLayout_5.addWidget(self.addTask)
        self.taskHistoryBtn = QtGui.QPushButton(self.layoutWidget)
        self.taskHistoryBtn.setObjectName(_fromUtf8("taskHistoryBtn"))
        self.horizontalLayout_5.addWidget(self.taskHistoryBtn)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 20)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 378, 311))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.scrollArea_3 = QtGui.QScrollArea(self.groupBox_4)
        self.scrollArea_3.setGeometry(QtCore.QRect(9, 9, 361, 291))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 359, 289))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.scrollAreaContentsWidget_3 = QtGui.QWidget(self.scrollAreaWidgetContents_3)
        self.scrollAreaContentsWidget_3.setGeometry(QtCore.QRect(-1, -1, 361, 291))
        self.scrollAreaContentsWidget_3.setObjectName(_fromUtf8("scrollAreaContentsWidget_3"))
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.tabWidget.addTab(self.tasksTab, _fromUtf8(""))
        self.dateTab = QtGui.QWidget()
        self.dateTab.setObjectName(_fromUtf8("dateTab"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.dateTab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 361, 331))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.gridLayoutWidget_2)
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.horizontalLayout_4.addWidget(self.dateTimeEdit)
        self.countdownStart = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.countdownStart.setObjectName(_fromUtf8("countdownStart"))
        self.horizontalLayout_4.addWidget(self.countdownStart)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.gridLayout_3.setRowStretch(0, 10)
        self.tabWidget.addTab(self.dateTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Chaos", None))
        self.timeLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt; font-weight:600;\">00:00</span></p></body></html>", None))
        self.stopBtn.setText(_translate("MainWindow", "Reset", None))
        self.startBtn.setText(_translate("MainWindow", "Start", None))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "mm:ss", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.timerTab), _translate("MainWindow", "Timer", None))
        self.timeLabel_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600;\">00:00:00</span></p></body></html>", None))
        self.stopBtn_2.setText(_translate("MainWindow", "Clear", None))
        self.lapBtn.setText(_translate("MainWindow", "Lap", None))
        self.startBtn_2.setText(_translate("MainWindow", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stopwatchTab), _translate("MainWindow", "Stopwatch", None))
        self.addAlarmBtn.setText(_translate("MainWindow", "Add Alarm", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.alarmTab), _translate("MainWindow", "Alarm", None))
        self.addTask.setText(_translate("MainWindow", "Add", None))
        self.taskHistoryBtn.setText(_translate("MainWindow", "History", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tasksTab), _translate("MainWindow", "Tasks", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">0 days 0 hours</span></p><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">0 minutes</span></p><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">0 seconds</span></p></body></html>", None))
        self.countdownStart.setText(_translate("MainWindow", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dateTab), _translate("MainWindow", "Countdown to Date", None))

